### ISSUE TITLE
create_cost_penalty not appearing in namespace of PEMsamplr

### ISSUE THREAD

**Issue by joshuasamuelevans** [bcgov/PEMsamplr#10]
When I try to run anything with PEMsamplr::create_cost_penalty I get a namespace error: 

library(PEMsamplr)
PEMsamplr::create_cost_penalty
Error: 'create_cost_penalty' is not an exported object from 'namespace:PEMsamplr'

**Comment by gcperk** [comment]
Thanks @joshuasamuelevans , I re-worked this and it should be working now.
