### ISSUE TITLE
PEMsamplr install error with new update

### ISSUE THREAD

**Issue by joshuasamuelevans** [bcgov/PEMsamplr#14]
When using the following code remotes::install_github("bcgov/PEMsamplr", build_vignettes = FALSE) I get this error:

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘SpatialEco’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

I reinstalled spatialEco just to ensure I have it installed before running again and I get the same error. I believe this is due to the case differences between 'SpatialEco' and spatialEco. Perhaps an older version of spatialEco was originally called 'Spatial Eco'?

**Comment by gcperk** [comment]
@joshuasamuelevans thanks for pointing this out. I am making a few changes this morning so will fix this! 
Appreciate the bug finds
