### ISSUE TITLE
build_site_transects error

### ISSUE THREAD

**Issue by joshuasamuelevans** [bcgov/PEMsamplr#16]
When using the build_site_transects function I get the following error: 

Error in `st_as_sf()`:
ℹ In argument: `which.min(cost)`.
ℹ In group 1: `slice_num = 1`, `point_num = 1`.
Caused by error:
! Can't subset elements with `which.min(cost)`.
✖ `which.min(cost)` must be numeric, not a <SpatRaster> object.
Run `rlang::last_error()` to see where the error occurred.

This is occurring at line 27 with the following command: 
  
sample_points_low_cost <- sample_points_rotations %>%
    dplyr::group_by(slice_num, point_num) %>%
    dplyr::filter(aoi == TRUE) %>%
    dplyr::slice(which.min(cost)) %>%
    dplyr::ungroup()
  
 This failure is caused by cost being a specified as a spatRaster by the function not a numeric object and there is no transformation within the function.

**Comment by joshuasamuelevans** [comment]
This is caused by a layer naming error. The spatRaster must have cost as its layer name or this error will generate. Having the code specify the name of the cost layer should avoid this problem.

**Comment by gcperk** [comment]
Thanks @joshuasamuelevans this is the new output of the leastcostpath version. I have added an update to the vignette.
