### ISSUE TITLE
check_bgc_landscapes error

### ISSUE THREAD

**Issue by joshuasamuelevans** [bcgov/PEMsamplr#9]
When running check_bgc_landscapes the function errored out with the following: 

**Error: [vect] cannot read this geometry type: Unknown (any)**

This was using the bec.gpkg created from the basedata functions. Reading in the gpkg as an sf object then converting to a spatVector fixed this issue. See code below:

`check_bgc_landscapes <- function(bec, binned_landscape){
  
  
  sfbgc <- sf::st_read(bec, quiet = T)
  vbgc <- terra::vect(sfbgc)
 

  rbgc <- terra::rasterize(vbgc, binned_landscape, field = "MAP_LABEL")
  

  rout <- c(rbgc, binned_landscape)
  routdf <- as.data.frame(rout)
  
  routdf <- na.omit(routdf)
  
  return(routdf)
  
}`

**Comment by gcperk** [comment]
Might need to double check the bgc layer = crs(3005). I can make an adjustment to double check this in the generate vector function. Thanks!
